// Enhancements: %HC labels on bars; PV theoretical daily chart with daylight lines; geoloc + city search; NOAA-like sunrise/sunset
const $ = (sel) => document.querySelector(sel);
const fmtEuro = (n) => n.toLocaleString('fr-FR', { style: 'currency', currency: 'EUR' });
const fmtNum = (n, d=3) => n.toLocaleString('fr-FR', { minimumFractionDigits: d, maximumFractionDigits: d });
const fmtPct = (n, d=0) => (n).toLocaleString('fr-FR', { style: 'percent', minimumFractionDigits: d, maximumFractionDigits: d });

// ---- Params & HC ----
function loadParams(){ try{ const p=JSON.parse(localStorage.getItem('hp_hc_params')||'{}'); ['prix_base','prix_hc','prix_hp','abo_base','abo_hphc'].forEach(id=>{$('#'+id).value=p[id]??''}); $('#ref_time').value=p.ref_time??'mid'; const hcList=$('#hc-list'); hcList.innerHTML=''; (p.plages_hc||[{debut:'22:30',fin:'06:30'}]).forEach(addHcRow); }catch{} }
function addHcRow(v){ const row=document.createElement('div'); row.className='hc-row'; row.innerHTML=`<label>Début <input type="time" value="${v?.debut||''}"/></label><label>Fin <input type="time" value="${v?.fin||''}"/></label><button class="sec" type="button">Supprimer</button>`; row.querySelector('button').onclick=()=>row.remove(); $('#hc-list').appendChild(row);} 
function collectParams(){ const plages=[...document.querySelectorAll('.hc-row')].map(r=>({debut:r.querySelectorAll('input')[0].value,fin:r.querySelectorAll('input')[1].value})).filter(p=>p.debut&&p.fin); const g=id=>parseFloat(($('#'+id).value||'').replace(',','.'))||0; return {prix_base:g('prix_base'),prix_hc:g('prix_hc'),prix_hp:g('prix_hp'),abo_base:g('abo_base'),abo_hphc:g('abo_hphc'),ref_time:$('#ref_time').value||'mid',plages_hc:plages}; }
['prix_base','prix_hc','prix_hp','abo_base','abo_hphc','ref_time','pv_power_w','pv_clear_factor','lat','lon'].forEach(id=>{ $('#'+id)?.addEventListener('input', ()=> recompute(true)); $('#'+id)?.addEventListener('change', ()=> recompute(true));});
$('#hc-list')?.addEventListener('change', ()=> recompute(true));
loadParams();
$('#btn-save')?.addEventListener('click',()=>{ localStorage.setItem('hp_hc_params',JSON.stringify(collectParams())); alert('Paramètres sauvegardés ✔'); });
$('#btn-clear')?.addEventListener('click',()=>{ localStorage.removeItem('hp_hc_params'); location.reload(); });

// ---- Geolocation & City search (Nominatim) ----
$('#btn-geoloc')?.addEventListener('click', ()=>{ if(!('geolocation' in navigator)){ alert('Géolocalisation non supportée par ce navigateur.'); return; } navigator.geolocation.getCurrentPosition(pos=>{ const {latitude, longitude} = pos.coords; $('#lat').value=latitude.toFixed(6); $('#lon').value=longitude.toFixed(6); recompute(true); }, err=>{ alert('Impossible d\'obtenir la position: '+(err?.message||'')); }); });
let cityTimer=null; const cityBox=$('#city_results'); $('#city_query')?.addEventListener('input', (e)=>{ const q=(e.target.value||'').trim(); if(cityTimer) clearTimeout(cityTimer); if(q.length<2){ cityBox.style.display='none'; cityBox.innerHTML=''; return; } cityTimer=setTimeout(async()=>{ try{ const url=`https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=5&accept-language=fr&q=${encodeURIComponent(q)}&countrycodes=fr`; const r=await fetch(url, { headers: { 'Accept-Language':'fr' } }); const js=await r.json(); if(!Array.isArray(js)||!js.length){ cityBox.innerHTML='<div class="muted" style="padding:8px">Aucun résultat</div>'; cityBox.style.display='block'; return; } let html='<table><thead><tr><th>Ville</th><th>Lat</th><th>Lon</th></tr></thead><tbody>'; js.forEach(it=>{ const name=it.display_name; html+=`<tr data-lat="${it.lat}" data-lon="${it.lon}" class="city-row" style="cursor:pointer"><td>${name}</td><td>${parseFloat(it.lat).toFixed(5)}</td><td>${parseFloat(it.lon).toFixed(5)}</td></tr>`; }); html+='</tbody></table>'; cityBox.innerHTML=html; cityBox.style.display='block'; [...cityBox.querySelectorAll('.city-row')].forEach(tr=>{ tr.addEventListener('click',()=>{ $('#lat').value=parseFloat(tr.getAttribute('data-lat')).toFixed(6); $('#lon').value=parseFloat(tr.getAttribute('data-lon')).toFixed(6); cityBox.style.display='none'; cityBox.innerHTML=''; recompute(true); }); }); }catch(err){ console.warn(err); } }, 700); });

// ---- CSV parsing (with metadata pairing) ----
function normalizeHeader(h){ return h.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim(); }
function detectDelimiter(line){ const count=(ch,str)=> (str.match(new RegExp(ch,'g'))||[]).length; const sc=count(';',line), cc=count(',',line), tc=count('\t',line); if(sc>=tc&&sc>=cc) return ';'; if(tc>=sc&&tc>=cc) return '\t'; return ','; }
function splitCSVLine(line,delim){ return line.split(delim).map(s=>s.trim()); }
function asNumberFR(s){ if(s==null) return NaN; s=(''+s).replace(/\s/g,'').replace(',','.'); return parseFloat(s); }
function parseCSVWithMeta(text){ const lines = text.split(/\r?\n/).filter(l=>l.length>0); if(!lines.length) return {headers:[],rows:[],meta:'',unit:null,pasMin:null,rawLines:[]}; let headerIdx=0; let delim=detectDelimiter(lines[0]); let unit=null, pasMin=null; for(let i=0;i<Math.min(80,lines.length-1);i++){ const d=detectDelimiter(lines[i]); const d2=detectDelimiter(lines[i+1]); const parts=splitCSVLine(lines[i],d).map(normalizeHeader); const vals=splitCSVLine(lines[i+1],d2); if(parts.includes('unite')){ const idxU=parts.indexOf('unite'); unit=(vals[idxU]||'').trim(); } if(parts.includes('pas en minutes')){ const idxP=parts.indexOf('pas en minutes'); const v=(vals[idxP]||'').trim(); if(/^\d+$/.test(v)) pasMin=parseInt(v,10); } const norm=parts.join(';'); if(norm==='horodate;valeur' || norm==='date;heure' || norm.includes('kwh') || norm.includes('wh') || norm.includes('kw')){ headerIdx=i; delim=d; break; } } if(unit==null || pasMin==null){ for(let i=0;i<Math.min(80,lines.length);i++){ if(unit==null){ const m=lines[i].match(/;Unite;([^;\n]*)/i); if(m) unit=(m[1]||'').trim(); } if(pasMin==null){ const m=lines[i].match(/;Pas en minutes;([^;\n]*)/i); if(m){ const v=(m[1]||'').trim(); if(/^\d+$/.test(v)) pasMin=parseInt(v,10); } } } } const rawHeaders = splitCSVLine(lines[headerIdx],delim); const headers=rawHeaders.map(normalizeHeader); const rows=[]; for(let i=headerIdx+1;i<lines.length;i++){ const parts=splitCSVLine(lines[i],delim); if(parts.length<2) continue; const obj={}; for(let j=0;j<rawHeaders.length;j++){ obj[headers[j]]=parts[j]||''; } rows.push(obj); } return {headers,rows,meta:lines.slice(0,headerIdx).join('\n'),unit,pasMin, rawLines: lines.slice(headerIdx, headerIdx+1+Math.min(10, rows.length+1))}; }

function renderPreview(container, parsed){ const wrap=$(container); if(!parsed||!parsed.headers||parsed.headers.length===0){ wrap.innerHTML=''; return; } let html='<div class="muted" style="margin-bottom:4px">Aperçu des premières lignes :</div><table><thead><tr>'; parsed.headers.forEach(h=>{ html+=`<th>${h}</th>`;}); html+='</tr></thead><tbody>'; for(let i=0;i<Math.min(5, parsed.rows.length); i++){ html+='<tr>'; parsed.headers.forEach(h=>{ html+=`<td>${parsed.rows[i][h]||''}</td>`;}); html+='</tr>'; } html+='</tbody></table>'; wrap.innerHTML=html; }

function transformData(parsed, forced){ const H=parsed.headers; const idx=(n)=>H.indexOf(n); const iHorodate=idx('horodate'); const iValeur=idx('valeur'); const iDate=idx('date'); const iHeure=Math.max(idx('heure'),idx('time'),idx('hour'),idx('heures')); const iKwh=Math.max(idx('energie (kwh)'),idx('énergie (kwh)'),idx('kwh'),idx('energie')); const iWh=Math.max(idx('wh'),idx('wattheure'),idx('watt-heures')); const iDebut=Math.max(idx('dateheure de debut'),idx('dateheure de début')); const iFin=Math.max(idx('datehaure de fin'),idx('dateheure de fin')); const iKW=Math.max(idx('valeur (en kw)'), idx('kw')); const rows=parsed.rows; let data=[]; let diag={format:'', unit:(forced.unit||parsed.unit||''), pas:(forced.step||parsed.pasMin||null), stepMin:null, count:0, first:null, last:null}; if(iHorodate>=0 && iValeur>=0){ const pts=rows.map(r=>({t:new Date(r['horodate']), v:asNumberFR(r['valeur'])})).filter(p=>!isNaN(p.t)&&isFinite(p.v)).sort((a,b)=>a.t-b.t); if(pts.length<2) throw new Error('Pas assez de points Horodate/Valeur'); const diffs=[]; for(let i=1;i<pts.length;i++){ diffs.push((pts[i].t-pts[i-1].t)/60000); } const med=diffs.sort((a,b)=>a-b)[Math.floor(diffs.length/2)]||15; const stepMin=(forced.step||parsed.pasMin||med); const dhDefault=stepMin/60; let unit=(forced.unit||parsed.unit||'W').toUpperCase(); for(let i=1;i<pts.length;i++){ const start=pts[i-1].t, end=pts[i].t; const dh=((end-start)/3600000)||dhDefault; let kwh; if(unit==='W') kwh=(pts[i].v*dh)/1000.0; else if(unit==='WH') kwh=pts[i].v/1000.0; else if(unit==='KWH') kwh=pts[i].v; else if(unit==='KW') kwh=pts[i].v*dh; else { kwh=(pts[i].v>=50? pts[i].v/1000.0 : pts[i].v); } data.push({start,end,kwh}); } diag.format='Horodate;Valeur'; diag.unit=unit; diag.stepMin=Math.round(stepMin); diag.count=data.length; diag.first=pts[0].t; diag.last=pts[pts.length-1].t; return {data, diag}; }
 if(iDebut>=0 && iFin>=0 && iKW>=0){ const pts=rows.map(r=>({s:new Date((r[H[iDebut]]||'').replace(/(\d{2})\/(\d{2})\/(\d{4})/,'$3-$2-$1')), e:new Date((r[H[iFin]]||'').replace(/(\d{2})\/(\d{2})\/(\d{4})/,'$3-$2-$1')), kw:asNumberFR(r[H[iKW]])})).filter(p=>!isNaN(p.s)&&!isNaN(p.e)&&isFinite(p.kw)).sort((a,b)=>a.s-b.s); pts.forEach(p=>{ const dh=(p.e-p.s)/3600000; data.push({start:p.s,end:p.e,kwh:p.kw*dh}); }); const stepMin=pts.length>1? Math.round((pts[1].e-pts[1].s)/60000):null; return {data, diag:{format:'Début/Fin/kW', unit:'kW', stepMin, count:data.length, first:pts[0]?.s||null, last:pts[pts.length-1]?.e||null}}; }
 if(iDate>=0 && iHeure>=0 && (iKwh>=0||iWh>=0)){ const pts=rows.map(r=>{ const dt=new Date(r['date'].replace(/(\d{2})\/(\d{2})\/(\d{4})/,'$3-$2-$1')+' '+r[H[iHeure]]); let kwh=NaN; if(iKwh>=0) kwh=asNumberFR(r[H[iKwh]]); else kwh=asNumberFR(r[H[iWh]])/1000.0; return {t:dt,kwh}; }).filter(p=>!isNaN(p.t)&&isFinite(p.kwh)).sort((a,b)=>a.t-b.t); const stepMin=(forced.step||60); for(let i=0;i<pts.length;i++){ const start=pts[i].t; const end=new Date(start.getTime()+stepMin*60000); data.push({start,end,kwh:pts[i].kwh}); } return {data, diag:{format:'Date/Heure/kWh|Wh', unit:(iWh>=0?'Wh':'kWh'), stepMin, count:data.length, first:pts[0]?.t||null, last:pts[pts.length-1]?.t||null}}; }
 throw new Error('Format non reconnu.'); }

function diagLine(name, d){ if(!d) return `${name}: —\n`; const f=(dt)=> dt? new Date(dt).toLocaleString('fr-FR'):'—'; return `${name}: format=${d.format}, unité=${d.unit||'auto'}, pas≈${d.stepMin||'auto'} min, points=${d.count}, début=${f(d.first)}, fin=${f(d.last)}`; }

// ---- State & events ----
const OV = { import: { unit: '', step: null }, export: { unit: '', step: null }, pv: { unit: '', step: null } };
const PARSED = { import: null, export: null, pv: null };
['import','export','pv'].forEach(kind=>{
  $('#ov-unit-'+kind)?.addEventListener('change', e=>{ OV[kind].unit = e.target.value || ''; applyOverrides(kind); });
  $('#ov-step-'+kind)?.addEventListener('input', e=>{ const v=parseInt(e.target.value,10); OV[kind].step = (isFinite(v) && v>0)? v : null; applyOverrides(kind); });
  $('#ov-step-'+kind)?.addEventListener('change', e=>{ const v=parseInt(e.target.value,10); OV[kind].step = (isFinite(v) && v>0)? v : null; applyOverrides(kind); });
});
let DATA_IMPORT=null, DATA_EXPORT=null, DATA_PV=null; let DIAG_IMPORT=null, DIAG_EXPORT=null, DIAG_PV=null; let LAST_SELECTED_YEAR=''; let LAST_SELECTED_MONTH='';
async function handleFile(inputSel, kind){ const el=$(inputSel); if(!el.files?.length){ setData(kind,null,null); PARSED[kind]=null; updateDiag(); recompute(true); return; } const text=await el.files[0].text(); const parsed=parseCSVWithMeta(text); PARSED[kind]=parsed; renderPreview('#preview-'+kind, parsed); const forced={ unit:(OV[kind].unit||''), step:(OV[kind].step||null) }; const {data,diag}=transformData(parsed, forced); setData(kind,data,diag); updateDiag(); recompute(true); }
function applyOverrides(kind){ const parsed=PARSED[kind]; if(!parsed) return; const forced={ unit:(OV[kind].unit||''), step:(OV[kind].step||null) }; try{ const {data,diag}=transformData(parsed, forced); setData(kind, data, diag); updateDiag(); recompute(true); }catch(err){ console.error(err); }}
function setData(kind, data, diag){ if(kind==='import'){ DATA_IMPORT=data; DIAG_IMPORT=diag; } else if(kind==='export'){ DATA_EXPORT=data; DIAG_EXPORT=diag; } else { DATA_PV=data; DIAG_PV=diag; } }
$('#file-import')?.addEventListener('change', ()=>handleFile('#file-import','import'));
$('#file-export')?.addEventListener('change', ()=>handleFile('#file-export','export'));
$('#file-pv')?.addEventListener('change', ()=>handleFile('#file-pv','pv'));
function updateDiag(){ const lines=[]; lines.push(diagLine('Consommation (import)', DIAG_IMPORT)); lines.push(diagLine('Injection (export)', DIAG_EXPORT)); lines.push(diagLine('Production PV', DIAG_PV)); $('#import_diag').textContent = lines.join('\n'); }

// ---- HC helpers ----
function toTimeNumber(d){ return d.getHours()/24 + d.getMinutes()/1440 + d.getSeconds()/86400; }
function parseTimeStr(hhmm){ const [h,m]=(hhmm||'0:0').split(':').map(x=>parseInt(x||'0',10)); return h/24 + (m||0)/1440; }
function inHC(t,ranges){ for(const [s,e] of ranges){ if(s<=e){ if(t>=s&&t<e) return true; } else { if(t>=s||t<e) return true; } } return false; }

// ---- Aggregations ----
const MONTHS_FR=['janv.','févr.','mars','avr.','mai','juin','juil.','août','sept.','oct.','nov.','déc.'];
function ym(d){ return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`; }
function ymd(d){ return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }
function monthLabel(key){ const [y,mm]=key.split('-'); return `${MONTHS_FR[parseInt(mm,10)-1]} ${y}`; }
function aggImportHPHC(records){ const p=collectParams(); const ranges=(p.plages_hc||[]).map(x=>[parseTimeStr(x.debut),parseTimeStr(x.fin)]); const ref=p.ref_time; const map=new Map(); let sumHP=0,sumHC=0; (records||[]).forEach(rec=>{ const t=(ref==='start')?rec.start:(ref==='end'?rec.end:new Date((rec.start.getTime()+rec.end.getTime())/2)); const key=ym(rec.start); const b=map.get(key)||{hp:0,hc:0}; if(inHC(toTimeNumber(t),ranges)){ b.hc+=rec.kwh; sumHC+=rec.kwh; } else { b.hp+=rec.kwh; sumHP+=rec.kwh; } map.set(key,b); }); return {map,sumHP,sumHC}; }
function aggSimple(records){ const m=new Map(); let tot=0; (records||[]).forEach(r=>{ const k=ym(r.start); m.set(k,(m.get(k)||0)+r.kwh); tot+=r.kwh; }); return {map:m,total:tot}; }
function aggDailySplit(year,month){ const p=collectParams(); const ranges=(p.plages_hc||[]).map(x=>[parseTimeStr(x.debut),parseTimeStr(x.fin)]); const ref=p.ref_time; const daily=new Map(); (DATA_IMPORT||[]).forEach(rec=>{ const d=rec.start; const y=d.getFullYear(), m=d.getMonth()+1; if(year && y!==year) return; if(month && m!==month) return; const t=(ref==='start')?rec.start:(ref==='end'?rec.end:new Date((rec.start.getTime()+rec.end.getTime())/2)); const key=ymd(rec.start); const b=daily.get(key)||{hp:0,hc:0,pv:0,ex:0}; if(inHC(toTimeNumber(t),ranges)) b.hc+=rec.kwh; else b.hp+=rec.kwh; daily.set(key,b); }); (DATA_PV||[]).forEach(r=>{ const d=r.start; const y=d.getFullYear(), m=d.getMonth()+1; if(year && y!==year) return; if(month && m!==month) return; const key=ymd(r.start); const b=daily.get(key)||{hp:0,hc:0,pv:0,ex:0}; b.pv+=r.kwh; daily.set(key,b); }); (DATA_EXPORT||[]).forEach(r=>{ const d=r.start; const y=d.getFullYear(), m=d.getMonth()+1; if(year && y!==year) return; if(month && m!==month) return; const key=ymd(r.start); const b=daily.get(key)||{hp:0,hc:0,pv:0,ex:0}; b.ex+=r.kwh; daily.set(key,b); }); const rows=[...daily.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([k,v])=>{ const pv_auto=Math.max(0, v.pv - v.ex); const importTot=v.hp+v.hc; const load=Math.max(0, v.pv + importTot - v.ex); return {date:k, hp:v.hp, hc:v.hc, importTot, pv:v.pv, exp:v.ex, pv_auto, load}; }); return rows; }

// ---- Colors ----
const COLOR_HC='#16a34a', COLOR_HP='#2563eb', COLOR_PV_AUTO='#f59e0b', COLOR_PV_THEO='#fb923c', COLOR_LINE='#ef4444', COLOR_LINE2='#6b7280';

// ---- Pie ----
function renderPie(elem,hc,hp){ const total=Math.max(1e-9,hc+hp); const vals=[hc,hp]; const cols=[COLOR_HC,COLOR_HP]; const r=110,cx=120,cy=120; let ang=-Math.PI/2; let svg=`<svg width="240" height="240" viewBox="0 0 240 240">`; vals.forEach((v,i)=>{ const a2=ang+(v/total)*2*Math.PI; const x1=cx+r*Math.cos(ang),y1=cy+r*Math.sin(ang); const x2=cx+r*Math.cos(a2),y2=cy+r*Math.sin(a2); const large=(a2-ang)>Math.PI?1:0; svg+=`<path d="M ${cx} ${cy} L ${x1} ${y1} A ${r} ${r} 0 ${large} 1 ${x2} ${y2} Z" fill="${cols[i]}" />`; const mid=(ang+a2)/2; const rx=cx+(r*0.6)*Math.cos(mid), ry=cy+(r*0.6)*Math.sin(mid); const pctText=((v/total)*100).toFixed(0)+'%'; svg+=`<text x="${rx}" y="${ry}" text-anchor="middle" dominant-baseline="middle" fill="#ffffff" font-size="13" font-weight="600">${pctText}</text>`; ang=a2; }); svg+='</svg>'; elem.innerHTML=svg; }
function renderPieLegend(container,hc,hp){ const total=Math.max(1e-9,hc+hp); container.innerHTML=''; const mk=(color,label,val)=>{ const pct=(val/total); const div=document.createElement('div'); div.className='chip'; div.innerHTML=`<span class="dot" style="background:${color}"></span><span>${label}</span><strong>${(pct*100).toFixed(0)}% · ${fmtNum(val,1)} kWh</strong>`; return div; }; container.appendChild(mk(COLOR_HC,'Heures Creuses',hc)); container.appendChild(mk(COLOR_HP,'Heures Pleines',hp)); }

// ---- Monthly bars (%HC annotations) ----
function drawStackedBars(elem, months){ const n=months.length; const margin={t:20,r:16,b:70,l:64}; const w=Math.max(420,n*60+margin.l+margin.r); const h=360; const maxV=Math.max(1,...months.map(m=>m.totalLoad)); const ih=h-margin.t-margin.b; const iw=w-margin.l-margin.r; const barW=Math.max(24,Math.min(56,Math.floor(iw/Math.max(1,n*1.08)))); const gap=Math.max(10,Math.floor(barW*0.22)); const scaleY=(v)=> margin.t+ih-(v/maxV)*ih; let svg=`<svg width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">`; for(let i=0;i<=4;i++){ const v=(maxV*i/4); const y=scaleY(v); svg+=`<line x1="${margin.l}" y1="${y}" x2="${w-margin.r}" y2="${y}" stroke="#e5edf5"/>`; svg+=`<text x="${margin.l-10}" y="${y}" text-anchor="end" dominant-baseline="middle" fill="#627d98" font-size="11">${v.toFixed(0)}</text>`;} svg+=`<line x1="${margin.l}" y1="${margin.t+ih}" x2="${w-margin.r}" y2="${margin.t+ih}" stroke="#9fb3c8"/>`; let x=margin.l+8; const yB=margin.t+ih; months.forEach(m=>{ const importTot=m.hp+m.hc; const hpH=yB-scaleY(m.hp); const hcH=yB-scaleY(m.hp+m.hc)-(yB-scaleY(m.hp)); const pvH=yB-scaleY(m.totalLoad)-(yB-scaleY(m.hp+m.hc)); const yHP=yB-hpH, yHC=yHP-hcH, yPV=yHC-pvH; const onclick=`onMonthBarClick('${m.key}')`; svg+=`<rect x="${x}" y="${yHP}" width="${barW}" height="${hpH}" rx="3" fill="${COLOR_HP}" style="cursor:pointer" onclick="${onclick}"></rect>`; svg+=`<rect x="${x}" y="${yHC}" width="${barW}" height="${hcH}" rx="3" fill="${COLOR_HC}" style="cursor:pointer" onclick="${onclick}"></rect>`; svg+=`<rect x="${x}" y="${yPV}" width="${barW}" height="${pvH}" rx="3" fill="${COLOR_PV_AUTO}" style="cursor:pointer" onclick="${onclick}"></rect>`; // %HC label
  const pctHC = importTot>0? Math.round(m.hc/importTot*100):0; svg+=`<text x="${x+barW/2}" y="${yHC-6}" text-anchor="middle" fill="#0f172a" font-size="11" font-weight="700">HC ${pctHC}%</text>`; svg+=`<text x="${x+barW/2}" y="${h-26}" text-anchor="middle" fill="#334e68" font-size="11">${m.label}</text>`; x+=barW+gap;}); elem.innerHTML=svg+'</svg>'; }
function renderStackedLegend(container){ container.innerHTML=''; const mk=(c,t)=>{const d=document.createElement('div'); d.className='chip'; d.innerHTML=`<span class="dot" style="background:${c}"></span><span>${t}</span>`; return d;}; container.appendChild(mk(COLOR_HP,'Heures Pleines (HP)')); container.appendChild(mk(COLOR_HC,'Heures Creuses (HC)')); container.appendChild(mk(COLOR_PV_AUTO,'PV autoconsommée')); }

// ---- Daily bars with %HC ----
function drawDailyBars(elem, days){ const n=days.length; const margin={t:20,r:12,b:70,l:64}; const w=Math.max(420,n*24+margin.l+margin.r); const h=320; const maxV=Math.max(1,...days.map(d=>d.load)); const ih=h-margin.t-margin.b; const iw=w-margin.l-margin.r; const barW=Math.max(10,Math.min(22,Math.floor(iw/Math.max(1,n*1.08)))); const gap=Math.max(6,Math.floor(barW*0.25)); const scaleY=(v)=> margin.t+ih-(v/maxV)*ih; let svg=`<svg width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">`; for(let i=0;i<=4;i++){ const v=(maxV*i/4); const y=scaleY(v); svg+=`<line x1="${margin.l}" y1="${y}" x2="${w-margin.r}" y2="${y}" stroke="#e5edf5"/>`; svg+=`<text x="${margin.l-10}" y="${y}" text-anchor="end" dominant-baseline="middle" fill="#627d98" font-size="10">${v.toFixed(0)}</text>`;} svg+=`<line x1="${margin.l}" y1="${margin.t+ih}" x2="${w-margin.r}" y2="${margin.t+ih}" stroke="#9fb3c8"/>`; let x=margin.l+8; const yB=margin.t+ih; days.forEach(d=>{ const importTot=d.hp+d.hc; const hpH=yB-scaleY(d.hp); const hcH=yB-scaleY(d.hp+d.hc)-(yB-scaleY(d.hp)); const pvH=yB-scaleY(d.load)-(yB-scaleY(d.hp+d.hc)); const yHP=yB-hpH, yHC=yHP-hcH, yPV=yHC-pvH; const label=d.date.slice(-2)+'/'+d.date.slice(5,7); svg+=`<rect x="${x}" y="${yHP}" width="${barW}" height="${hpH}" rx="2" fill="${COLOR_HP}"></rect>`; svg+=`<rect x="${x}" y="${yHC}" width="${barW}" height="${hcH}" rx="2" fill="${COLOR_HC}"></rect>`; svg+=`<rect x="${x}" y="${yPV}" width="${barW}" height="${pvH}" rx="2" fill="${COLOR_PV_AUTO}"></rect>`; const pctHC = importTot>0? Math.round(d.hc/importTot*100):0; svg+=`<text x="${x+barW/2}" y="${yHC-5}" text-anchor="middle" fill="#0f172a" font-size="9" font-weight="700">${pctHC}%</text>`; svg+=`<text x="${x+barW/2}" y="${h-24}" text-anchor="middle" fill="#334e68" font-size="9">${label}</text>`; x+=barW+gap;}); elem.innerHTML=svg+'</svg>'; }

// ---- NOAA-like sunrise/sunset (approx) ----
function toRadians(d){ return d*Math.PI/180; } function toDegrees(r){ return r*180/Math.PI; }
function jday(y,m,d){ const A=Math.floor((14-m)/12); const Y=y+4800-A; const M=m+12*A-3; return d + Math.floor((153*M+2)/5) + 365*Y + Math.floor(Y/4) - Math.floor(Y/100) + Math.floor(Y/400) - 32045; }
function sunDeclination(n){ const g = toRadians(357.529 + 0.98560028*n); const q = toRadians(280.459 + 0.98564736*n); const L = q + toRadians(1.915)*Math.sin(g) + toRadians(0.020)*Math.sin(2*g); const e = toRadians(23.439 - 0.00000036*n); const dec = Math.asin(Math.sin(e)*Math.sin(L)); return dec; }
function eqtime(n){ const g=toRadians(357.529 + 0.98560028*n); const q=toRadians(280.459 + 0.98564736*n); const L=q + toRadians(1.915)*Math.sin(g) + toRadians(0.020)*Math.sin(2*g); const e=toRadians(23.439 - 0.00000036*n); const RA=Math.atan2(Math.cos(e)*Math.sin(L), Math.cos(L)); const E = q - RA; return (toDegrees(E) - 360*Math.round(toDegrees(E)/360)) * 4; }
function srss(date, lat, lon){ // returns {sunrise: Date, sunset: Date, daylightHours}
  // Based on USNO/NOAA style approximations
  const J = jday(date.getFullYear(), date.getMonth()+1, date.getDate()); const n = J - 2451545.0; const dec = sunDeclination(n); const eqt = eqtime(n); const latr=toRadians(lat); const zenith = toRadians(90.833); const cosH = (Math.cos(zenith) - Math.sin(latr)*Math.sin(dec)) / (Math.cos(latr)*Math.cos(dec)); if(cosH<=-1){ // polar day
    return {sunrise:null, sunset:null, daylightHours:24}; } else if(cosH>=1){ // polar night
    return {sunrise:null, sunset:null, daylightHours:0}; }
  const H = Math.acos(cosH); const Hdeg = toDegrees(H); // in degrees
  const sunriseMinutes = 720 - 4*(lon + Hdeg) - eqt; const sunsetMinutes = 720 - 4*(lon - Hdeg) - eqt; function minutesToLocalDate(mins){ const d=new Date(date); const hh=Math.floor(mins/60); const mm=Math.floor(mins%60); d.setHours(0,0,0,0); d.setMinutes(hh*60+mm); return d; }
  const sr = minutesToLocalDate(sunriseMinutes); const ss = minutesToLocalDate(sunsetMinutes); const daylight=(sunsetMinutes - sunriseMinutes)/60; return {sunrise:sr, sunset:ss, daylightHours:Math.max(0,Math.min(24,daylight))}; }

// ---- Theoretical PV & daylight lines ----
function drawTheoChart(elem, year, month, pvW, clearF, lat, lon){ const days=[]; const d0=new Date(year, month-1, 1); const d1=new Date(year, month, 0); for(let d=1; d<=d1.getDate(); d++){ const dt=new Date(year, month-1, d); const astro=srss(dt, lat, lon); const kwh = (pvW/1000.0) * astro.daylightHours * (clearF||0.5); days.push({date:dt, kwh, daylight:astro.daylightHours, sunrise:astro.sunrise, sunset:astro.sunset}); }
  const n=days.length; const margin={t:24,r:50,b:70,l:64}; const w=Math.max(420,n*24+margin.l+margin.r); const h=320; const maxKWh=Math.max(1,...days.map(d=>d.kwh)); const ih=h-margin.t-margin.b; const iw=w-margin.l-margin.r; const barW=Math.max(10,Math.min(22,Math.floor(iw/Math.max(1,n*1.08)))); const gap=Math.max(6,Math.floor(barW*0.25)); const scaleYk=(v)=> margin.t+ih-(v/maxKWh)*ih; const scaleYh=(v)=> margin.t+ih-(v/24)*ih; let svg=`<svg width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">`;
  // axes
  for(let i=0;i<=4;i++){ const v=(maxKWh*i/4); const y=scaleYk(v); svg+=`<line x1="${margin.l}" y1="${y}" x2="${w-margin.r}" y2="${y}" stroke="#e5edf5"/>`; svg+=`<text x="${margin.l-10}" y="${y}" text-anchor="end" dominant-baseline="middle" fill="#627d98" font-size="10">${v.toFixed(1)} kWh</text>`; }
  // right axis hours 0..24
  for(let i=0;i<=4;i++){ const vh=(24*i/4); const y=scaleYh(vh); svg+=`<text x="${w-margin.r+4}" y="${y}" text-anchor="start" dominant-baseline="middle" fill="#6b7280" font-size="10">${vh.toFixed(0)} h</text>`; }
  svg+=`<line x1="${margin.l}" y1="${margin.t+ih}" x2="${w-margin.r}" y2="${margin.t+ih}" stroke="#9fb3c8"/>`;
  let x=margin.l+8; const yB=margin.t+ih; const ptsDur=[]; const ptsSr=[]; const ptsSs=[]; days.forEach(d=>{ const kH=yB-scaleYk(d.kwh); const yBar=yB-kH; svg+=`<rect x="${x}" y="${yBar}" width="${barW}" height="${kH}" rx="2" fill="${COLOR_PV_THEO}"></rect>`; const lab=`${String(d.date.getDate()).padStart(2,'0')}/${String(d.date.getMonth()+1).padStart(2,'0')}`; svg+=`<text x="${x+barW/2}" y="${h-24}" text-anchor="middle" fill="#334e68" font-size="9">${lab}</text>`;
    const durY=scaleYh(d.daylight); ptsDur.push(`${x+barW/2},${durY}`);
    if(d.sunrise&&d.sunset){ const srH=d.sunrise.getHours()+d.sunrise.getMinutes()/60; const ssH=d.sunset.getHours()+d.sunset.getMinutes()/60; ptsSr.push(`${x+barW/2},${scaleYh(srH)}`); ptsSs.push(`${x+barW/2},${scaleYh(ssH)}`); }
    x+=barW+gap; });
  if(ptsDur.length) svg+=`<polyline fill="none" stroke="#10b981" stroke-width="2" points="${ptsDur.join(' ')}"/>`;
  if(ptsSr.length) svg+=`<polyline fill="none" stroke="${COLOR_LINE2}" stroke-width="1.5" stroke-dasharray="4 3" points="${ptsSr.join(' ')}"/>`;
  if(ptsSs.length) svg+=`<polyline fill="none" stroke="${COLOR_LINE}" stroke-width="1.5" stroke-dasharray="4 3" points="${ptsSs.join(' ')}"/>`;
  svg+='</svg>'; elem.innerHTML=svg; }

function renderTheoLegend(container){ container.innerHTML=''; const mk=(c,t)=>{ const d=document.createElement('div'); d.className='chip'; d.innerHTML=`<span class="dot" style="background:${c}"></span><span>${t}</span>`; return d;}; container.appendChild(mk(COLOR_PV_THEO,'PV théorique (kWh)')); container.appendChild(mk('#10b981','Durée d’ensoleillement (h)')); container.appendChild(mk(COLOR_LINE2,'Lever de soleil (heure)')); container.appendChild(mk(COLOR_LINE,'Coucher de soleil (heure)')); }

// ---- Core recompute ----
function recompute(preserve=false){ if(!DATA_IMPORT){ $('#results').classList.add('hidden'); $('#no-data').classList.remove('hidden'); return; } if(preserve){ LAST_SELECTED_YEAR=$('#year_select')?.value||''; LAST_SELECTED_MONTH=$('#month_select')?.value||''; }
  const p=collectParams(); const imp=aggImportHPHC(DATA_IMPORT); const exp=aggSimple(DATA_EXPORT||[]); const pv=aggSimple(DATA_PV||[]); const SUM_HP=imp.sumHP, SUM_HC=imp.sumHC; const TOT_IMPORT=SUM_HP+SUM_HC; const TOT_EXPORT=exp.total, TOT_PV=pv.total; const PV_AUTO=Math.max(0, TOT_PV - TOT_EXPORT); const LOAD=Math.max(0, TOT_PV + TOT_IMPORT - TOT_EXPORT); const pv_share=LOAD>0? PV_AUTO/LOAD:0; $('#tot_import').textContent=fmtNum(TOT_IMPORT,3)+' kWh'; $('#tot_pv').textContent=(TOT_PV>0?fmtNum(TOT_PV,3)+' kWh':'—'); $('#tot_export').textContent=(TOT_EXPORT>0?fmtNum(TOT_EXPORT,3)+' kWh':'—'); $('#tot_pv_auto').textContent=(PV_AUTO>0?fmtNum(PV_AUTO,3)+' kWh':'—'); $('#tot_load').textContent=(LOAD>0?fmtNum(LOAD,3)+' kWh':'—'); $('#pv_share').textContent=(LOAD>0?fmtPct(pv_share):'—'); renderPie($('#pie'), SUM_HC, SUM_HP); renderPieLegend($('#pie_legend'), SUM_HC, SUM_HP);
  // Abos global
  let minDate=DATA_IMPORT[0].start, maxDate=DATA_IMPORT[DATA_IMPORT.length-1].start; const jours=minDate&&maxDate? Math.floor((new Date(maxDate.toDateString())-new Date(minDate.toDateString()))/86400000)+1:0; const moisApprox=jours>0?(jours/30.0):0; const cout_base=TOT_IMPORT*p.prix_base; const cout_hphc=SUM_HC*p.prix_hc + SUM_HP*p.prix_hp; const tot_base_abos=cout_base + (p.abo_base||0)*moisApprox; const tot_hphc_abos=cout_hphc + (p.abo_hphc||0)*moisApprox; $('#tot_base_abos').textContent=fmtEuro(tot_base_abos); $('#tot_hphc_abos').textContent=fmtEuro(tot_hphc_abos); $('#eco_abos').textContent=fmtEuro(tot_base_abos - tot_hphc_abos);
  // Selectors
  const years=[...new Set([ ...imp.map.keys(), ...exp.map.keys(), ...pv.map.keys() ].map(k=>parseInt(k.split('-')[0],10)))].sort((a,b)=>a-b); const selY=$('#year_select'); selY.innerHTML=''; const oAllY=document.createElement('option'); oAllY.value=''; oAllY.textContent='Toutes'; selY.appendChild(oAllY); years.forEach(y=>{ const o=document.createElement('option'); o.value=String(y); o.textContent=String(y); selY.appendChild(o); }); if(preserve) selY.value=LAST_SELECTED_YEAR; const selM=$('#month_select'); selM.innerHTML=''; const oAllM=document.createElement('option'); oAllM.value=''; oAllM.textContent='Tous'; selM.appendChild(oAllM); for(let m=1;m<=12;m++){ const o=document.createElement('option'); o.value=String(m).padStart(2,'0'); o.textContent=String(m).padStart(2,'0'); selM.appendChild(o);} if(preserve) selM.value=LAST_SELECTED_MONTH; selY.onchange=()=>{ $('#daily_panel').classList.add('hidden'); LAST_SELECTED_MONTH=''; selM.value=''; refreshMonthly(imp.map, exp.map||new Map(), pv.map||new Map()); }; selM.onchange=()=>{ $('#daily_panel').classList.add('hidden'); refreshMonthly(imp.map, exp.map||new Map(), pv.map||new Map()); };
  refreshMonthly(imp.map, exp.map||new Map(), pv.map||new Map()); $('#results').classList.remove('hidden'); $('#no-data').classList.add('hidden'); $('#btn-export').onclick=()=>exportCSV(DATA_IMPORT, DATA_EXPORT, DATA_PV);
}

function refreshMonthly(impMap, expMap, pvMap){ const ySel=$('#year_select').value; const mSel=$('#month_select').value; LAST_SELECTED_YEAR=ySel; LAST_SELECTED_MONTH=mSel; const yr=ySel?parseInt(ySel,10):null; const mo=mSel?parseInt(mSel,10):null; const keys=[...new Set([ ...impMap.keys(), ...expMap.keys(), ...pvMap.keys() ])].sort(); const rows=[]; keys.forEach(k=>{ const [yy,mm]=k.split('-'); const y=parseInt(yy,10), m=parseInt(mm,10); if(yr&&y!==yr) return; if(mo&&m!==mo) return; const hp=(impMap.get(k)?.hp)||0, hc=(impMap.get(k)?.hc)||0, pv=pvMap.get(k)||0, ex=expMap.get(k)||0; const pv_auto=Math.max(0, pv-ex); const totalLoad=Math.max(0, pv + hp + hc - ex); rows.push({key:k,label:monthLabel(k),hp,hc,pv_auto,totalLoad,pv,exp:ex}); }); drawStackedBars($('#monthly_chart'), rows); renderStackedLegend($('#bar_legend'));
  // KPIs & economies filtered
  const p=collectParams(); let sumHP=0,sumHC=0,sumPV=0,sumEX=0,sumPVauto=0,sumLoad=0; rows.forEach(r=>{ sumHP+=r.hp; sumHC+=r.hc; sumPV+=r.pv; sumEX+=r.exp; sumPVauto+=r.pv_auto; sumLoad+=r.totalLoad; }); const totImport=sumHP+sumHC; const totPV=sumPV; const totExport=sumEX; const pvShare=sumLoad>0?(sumPVauto/sumLoad):0; $('#tot_import').textContent=fmtNum(totImport,3)+' kWh'; $('#tot_pv').textContent=(totPV>0?fmtNum(totPV,3)+' kWh':'—'); $('#tot_export').textContent=(totExport>0?fmtNum(totExport,3)+' kWh':'—'); $('#tot_pv_auto').textContent=(sumPVauto>0?fmtNum(sumPVauto,3)+' kWh':'—'); $('#tot_load').textContent=(sumLoad>0?fmtNum(sumLoad,3)+' kWh':'—'); $('#pv_share').textContent=(sumLoad>0?fmtPct(pvShare):'—'); renderPie($('#pie'), sumHC, sumHP); renderPieLegend($('#pie_legend'), sumHC, sumHP);
  // Tarifs detail
  const monthsCount=rows.length; const cout_base = totImport * p.prix_base; const cout_hc = sumHC * p.prix_hc; const cout_hp = sumHP * p.prix_hp; const cout_hphc = cout_hc + cout_hp; const abo_base = (p.abo_base||0)*monthsCount; const abo_hphc=(p.abo_hphc||0)*monthsCount; const tot_base_abos = cout_base + abo_base; const tot_hphc_abos = cout_hphc + abo_hphc; const eco_abos = tot_base_abos - tot_hphc_abos; $('#d_hc_kwh').textContent = fmtNum(sumHC,3); $('#d_prix_hc').textContent = fmtNum(p.prix_hc,4); $('#d_cout_hc').textContent = fmtEuro(cout_hc); $('#d_hp_kwh').textContent = fmtNum(sumHP,3); $('#d_prix_hp').textContent = fmtNum(p.prix_hp,4); $('#d_cout_hp').textContent = fmtEuro(cout_hp); $('#d_import_kwh').textContent = fmtNum(totImport,3); $('#d_prix_base').textContent = fmtNum(p.prix_base,4); $('#d_cout_base_energie').textContent = fmtEuro(cout_base); $('#d_abo_base').textContent = fmtNum(p.abo_base,2); $('#d_mois_base').textContent = String(monthsCount); $('#d_cout_abo_base').textContent = fmtEuro(abo_base); $('#d_abo_hphc').textContent = fmtNum(p.abo_hphc,2); $('#d_mois_hphc').textContent = String(monthsCount); $('#d_cout_abo_hphc').textContent = fmtEuro(abo_hphc); $('#d_tot_base').textContent = fmtEuro(tot_base_abos); $('#d_tot_hphc').textContent = fmtEuro(tot_hphc_abos); $('#d_eco_abos').textContent = fmtEuro(eco_abos); $('#tot_base_abos').textContent = fmtEuro(tot_base_abos); $('#tot_hphc_abos').textContent = fmtEuro(tot_hphc_abos); $('#eco_abos').textContent = fmtEuro(eco_abos);
  // If daily open, refresh
  if(!$('#daily_panel').classList.contains('hidden') && LAST_SELECTED_YEAR && LAST_SELECTED_MONTH){ const yr=parseInt(LAST_SELECTED_YEAR||'0',10)||null; const mo=parseInt(LAST_SELECTED_MONTH||'0',10)||null; if(yr&&mo){ showDailyFor(yr, mo, true); } }
  // Export
  $('#btn-export-monthly').onclick=()=>{ let csv='mois;kWh_HP;kWh_HC;kWh_PV_auto;kWh_PV_total;kWh_export;kWh_charge_total;%PV_sur_charge\n'; rows.forEach(m=>{ const pct=m.totalLoad>0? Math.round(m.pv_auto/m.totalLoad*100):0; csv += `${m.label};${m.hp.toFixed(3).replace('.',',')};${m.hc.toFixed(3).replace('.',',')};${m.pv_auto.toFixed(3).replace('.',',')};${m.pv.toFixed(3).replace('.',',')};${m.exp.toFixed(3).replace('.',',')};${m.totalLoad.toFixed(3).replace('.',',')};${pct}\n`;}); const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=`mensuel_hp_hc_pv${yr?('_'+yr):''}${mo?('_'+String(mo).padStart(2,'0')):''}.csv`; a.click(); URL.revokeObjectURL(url); };
}

function onMonthBarClick(key){ const [y,mm]=key.split('-'); const yr=parseInt(y,10), mo=parseInt(mm,10); $('#year_select').value=String(yr); $('#month_select').value=String(mo).padStart(2,'0'); refreshMonthly(aggImportHPHC(DATA_IMPORT).map, aggSimple(DATA_EXPORT||[]).map||new Map(), aggSimple(DATA_PV||[]).map||new Map()); showDailyFor(yr, mo); }
window.onMonthBarClick = onMonthBarClick;

function showDailyFor(year, month, silent){ const days=aggDailySplit(year, month); const title=`Détails jour par jour — ${String(month).padStart(2,'0')}/${year}`; $('#daily_title').textContent=title; const wrapTbl=$('#daily_table'); const wrapChart=$('#daily_chart'); const legend=$('#daily_legend'); if(!days.length){ wrapTbl.innerHTML='<div class="muted" style="padding:8px">Aucune donnée pour ce mois.</div>'; wrapChart.innerHTML=''; legend.innerHTML=''; if(!silent) $('#daily_panel').classList.remove('hidden'); return; }
  drawDailyBars(wrapChart, days); renderStackedLegend(legend);
  // Theoretical PV chart
  const pvW=parseFloat(($('#pv_power_w').value||'3000').replace(',','.'))||3000; const clearF=Math.min(1,Math.max(0, parseFloat(($('#pv_clear_factor').value||'0.5').replace(',','.'))||0.5)); const lat=parseFloat(($('#lat').value||'').replace(',','.')); const lon=parseFloat(($('#lon').value||'').replace(',','.'));
  if(isFinite(lat)&&isFinite(lon)){ drawTheoChart($('#theo_chart'), year, month, pvW, clearF, lat, lon); renderTheoLegend($('#theo_legend')); } else { $('#theo_chart').innerHTML='<div class="muted" style="padding:8px">Pour le PV théorique, renseignez la position (géoloc, ville ou lat/lon).</div>'; $('#theo_legend').innerHTML=''; }
  // Table
  let html='<div class="muted" style="margin-bottom:4px">Tableau par jour (kWh)</div><table><thead><tr><th>Date</th><th>HP</th><th>HC</th><th>Import</th><th>PV auto</th><th>Charge</th></tr></thead><tbody>'; days.forEach(d=>{ html+=`<tr><td>${d.date}</td><td>${d.hp.toFixed(3).replace('.',',')}</td><td>${d.hc.toFixed(3).replace('.',',')}</td><td>${d.importTot.toFixed(3).replace('.',',')}</td><td>${d.pv_auto.toFixed(3).replace('.',',')}</td><td>${d.load.toFixed(3).replace('.',',')}</td></tr>`; }); html+='</tbody></table>'; wrapTbl.innerHTML=html; if(!silent) $('#daily_panel').classList.remove('hidden'); }
$('#btn-daily-close')?.addEventListener('click', ()=>{ $('#daily_panel').classList.add('hidden'); });

// ---- Export ----
function exportCSV(importRows, exportRows, pvRows){ const header=['type','start','end','kWh']; const toCSV=(v)=>{ if(v==null) return ''; if(v instanceof Date) return v.toISOString(); if(typeof v==='number') return (''+v).replace('.',','); return '"'+String(v).replaceAll('"','""')+'"'; }; let csv=header.join(';')+'\n'; (importRows||[]).forEach(r=>{ csv += ['import', r.start, r.end, r.kwh].map(toCSV).join(';')+'\n'; }); (exportRows||[]).forEach(r=>{ csv += ['export', r.start, r.end, r.kwh].map(toCSV).join(';')+'\n'; }); (pvRows||[]).forEach(r=>{ csv += ['pv', r.start, r.end, r.kwh].map(toCSV).join(';')+'\n'; }); const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='donnees_calculees_hp_hc_pv.csv'; a.click(); URL.revokeObjectURL(url); }
